### ISSUE TITLE
Compare with dorment list only?

### ISSUE THREAD

**Issue by strickland** [mkhaled87/DormantBitcoinHunter#2]
Hey I was trying your python script and I thought if it only compares to the list of 100 addresses with lots of bitcoin then there may be a waste of other addresses which aren't in the list but may as well hold some bitcoins in them? Is there anyway to make it give an output in the keys.txt whenever it finds any private key that holds any bitcoin 1+ 

i.e. 

if it has 1+ bitcoin, then write the private key.

**Comment by mkhaled87** [comment]
Hi, Yes. you can replace the addresses list (addresses.py) with a shorter one if you like. Just collect the 100 addresses you like to concentrate the search on, and replace the file with one that has only 100 addresses. The script already outputs the found key in a file specified by "OUT_FILE" in the (env.py). You may update the script to print further info if you like,

**Comment by strickland** [comment]
Sorry I think you didn't understood my question.

I suggested not to be limited to 100 or 1000 wallets. In other words I don't want to add wallet addresses. How about a script that scans for ALL private keys and wallet addresses, then checks on blockchain if that wallet contains 1+ bitcoin then put it in the txt file.

Thats what I suggest.

**Comment by mkhaled87** [comment]
The space of private keys is so large that makes the search problem intractable. It is programmatically doable but you will not be able to find any match.

**Comment by strickland** [comment]
Thanks for the response again, but I find what you say a little bit curious which brings up yet another question. You say that "the space is large and you will not  be able to find any match." I do agree that space is large but that being said.  Please correct me if I'm wrong but with your method you are scanning throughout all the private keys and their corresponding wallet addresses then also checking with the list of dormant keys which has a lot of bitcoins in them and if there's a match it will print it into the txt file correct?
But with the method I said, it goes through the same exact scan of wallets and their corresponding private keys but in the same time checks with the blockchain site if the wallets has some funds in them, if the answer is yes then it prints it to the txt file.

Now with these two examples which one is more likely to find a private key. I would say its mine because in both cases I am scanning the entire space of wallets/private keys, but with mine I got more chances because it checks within all the space of wallets with funds, but with your way it only checks with 100 addresses that got a wale/large bitcoin size.

Unless I am understanding this wrong, I do believe that it is hard to find any match with both methods but which one of the two is more likely to find? The thing that raised this thought for me is while doing running the python script I asked myself what if throughout this scanning it already stumbled upon some wallets with 5 or 10 bitcoins but it doesn't print it out for me, isn't that a waste? because here I am only checking against a list of dormant of 100 addresses only. Do you see what I mean man? Sorry for the long msg but I just feel that you are not getting exactly what I mean.

**Comment by mkhaled87** [comment]
Hi,

First, I’d like to highlight that the python program is not going over all private keys. The private keys are generated randomaly.

Second, to give you an idea how big the space is, the number of all possible private keys is 2^256. On the other hand, it is estimated that there are around 2^63 grains of sand on all of the beaches of Earth combined. Hence, searching this space is currently not possible.

Third, if you scan the addresses and keep checking the balances online, you will incur a delay of communicating to the Bitcoin network to retrieve the balance of each address generated. This will dramatically slow the search. Here, we store the most valuable addresses and their balances locally in a fast-to-search data-structure to cut down that very-long query time.

Finally, and as I stated in the repo, this project is developed for fun. There is an almost-zero probability you can get any result out from it! If you catch a match, you are almost 2^256 luckier than an average person!


From: strickland ***@***.***>
Reply-To: mkhaled87/DormantBitcoinHunter ***@***.***>
Date: Tuesday, 2. November 2021 at 21:31
To: mkhaled87/DormantBitcoinHunter ***@***.***>
Cc: Mahmoud Khaled ***@***.***>, State change ***@***.***>
Subject: Re: [mkhaled87/DormantBitcoinHunter] Compare with dorment list only? (Issue #2)


Thanks for the response again, but I find what you say a little bit curious which brings up yet another question. You say that "the space is large and you will not be able to find any match." I do agree that space is large but that being said. Please correct me if I'm wrong but with your method you are scanning throughout all the private keys and their corresponding wallet addresses then also checking with the list of dormant keys which has a lot of bitcoins in them and if there's a match it will print it into the txt file correct?
But with the method I said, it goes through the same exact scan of wallets and their corresponding private keys but in the same time checks with the blockchain site if the wallets has some funds in them, if the answer is yes then it prints it to the txt file.

Now with these two examples which one is more likely to find a private key. I would say its mine because in both cases I am scanning the entire space of wallets/private keys, but with mine I got more chances because it checks within all the space of wallets with funds, but with your way it only checks with 100 addresses that got a wale/large bitcoin size.

Unless I am understanding this wrong, I do believe that it is hard to find any match with both methods but which one of the two is more likely to find? The thing that raised this thought for me is while doing running the python script I asked myself what if throughout this scanning it already stumbled upon some wallets with 5 or 10 bitcoins but it doesn't print it out for me, isn't that a waste? because here I am only checking against a list of dormant of 100 addresses only. Do you see what I mean man? Sorry for the long msg but I just feel that you are not getting exactly what I mean.
